language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t itismelmir/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true itismelmir/docker-react npm run test