language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t itismelmir/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true itismelmir/docker-react npm run test
deploy:
  provider: heroku
  api_key:
    secure: "4a01aac5-da6b-43fa-a7bc-7b91098e99a9"
  app: docker-reactjs
